try:
    from .h3_icr.adapter_nodes import NODE_CLASS_MAPPINGS as ADAPTER_NODE_CLASS_MAPPINGS
    from .h3_icr.adapter_nodes import NODE_DISPLAY_NAME_MAPPINGS as ADAPTER_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.attention_nodes import NODE_CLASS_MAPPINGS as ATTN_NODE_CLASS_MAPPINGS
    from .h3_icr.attention_nodes import NODE_DISPLAY_NAME_MAPPINGS as ATTN_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
    from .h3_icr.nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.pixel_nodes import NODE_CLASS_MAPPINGS as PIXEL_NODE_CLASS_MAPPINGS
    from .h3_icr.pixel_nodes import NODE_DISPLAY_NAME_MAPPINGS as PIXEL_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.posterior_nodes import NODE_CLASS_MAPPINGS as POSTERIOR_NODE_CLASS_MAPPINGS
    from .h3_icr.posterior_nodes import NODE_DISPLAY_NAME_MAPPINGS as POSTERIOR_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.sparse_nodes import NODE_CLASS_MAPPINGS as SPARSE_NODE_CLASS_MAPPINGS
    from .h3_icr.sparse_nodes import NODE_DISPLAY_NAME_MAPPINGS as SPARSE_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.tiled_nodes import NODE_CLASS_MAPPINGS as TILED_NODE_CLASS_MAPPINGS
    from .h3_icr.tiled_nodes import NODE_DISPLAY_NAME_MAPPINGS as TILED_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.upscaler_nodes import NODE_CLASS_MAPPINGS as UPSCALER_NODE_CLASS_MAPPINGS
    from .h3_icr.upscaler_nodes import NODE_DISPLAY_NAME_MAPPINGS as UPSCALER_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.validation_metric_nodes import NODE_CLASS_MAPPINGS as VALIDATION_METRIC_NODE_CLASS_MAPPINGS
    from .h3_icr.validation_metric_nodes import NODE_DISPLAY_NAME_MAPPINGS as VALIDATION_METRIC_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.validation_nodes import NODE_CLASS_MAPPINGS as VALIDATION_NODE_CLASS_MAPPINGS
    from .h3_icr.validation_nodes import NODE_DISPLAY_NAME_MAPPINGS as VALIDATION_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.validation_perf_nodes import NODE_CLASS_MAPPINGS as VALIDATION_PERF_NODE_CLASS_MAPPINGS
    from .h3_icr.validation_perf_nodes import NODE_DISPLAY_NAME_MAPPINGS as VALIDATION_PERF_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:  # allows source-tree test collection where root is imported as __init__
    from h3_icr.adapter_nodes import NODE_CLASS_MAPPINGS as ADAPTER_NODE_CLASS_MAPPINGS
    from h3_icr.adapter_nodes import NODE_DISPLAY_NAME_MAPPINGS as ADAPTER_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.attention_nodes import NODE_CLASS_MAPPINGS as ATTN_NODE_CLASS_MAPPINGS
    from h3_icr.attention_nodes import NODE_DISPLAY_NAME_MAPPINGS as ATTN_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
    from h3_icr.nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.pixel_nodes import NODE_CLASS_MAPPINGS as PIXEL_NODE_CLASS_MAPPINGS
    from h3_icr.pixel_nodes import NODE_DISPLAY_NAME_MAPPINGS as PIXEL_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.posterior_nodes import NODE_CLASS_MAPPINGS as POSTERIOR_NODE_CLASS_MAPPINGS
    from h3_icr.posterior_nodes import NODE_DISPLAY_NAME_MAPPINGS as POSTERIOR_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.sparse_nodes import NODE_CLASS_MAPPINGS as SPARSE_NODE_CLASS_MAPPINGS
    from h3_icr.sparse_nodes import NODE_DISPLAY_NAME_MAPPINGS as SPARSE_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.tiled_nodes import NODE_CLASS_MAPPINGS as TILED_NODE_CLASS_MAPPINGS
    from h3_icr.tiled_nodes import NODE_DISPLAY_NAME_MAPPINGS as TILED_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.upscaler_nodes import NODE_CLASS_MAPPINGS as UPSCALER_NODE_CLASS_MAPPINGS
    from h3_icr.upscaler_nodes import NODE_DISPLAY_NAME_MAPPINGS as UPSCALER_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.validation_metric_nodes import NODE_CLASS_MAPPINGS as VALIDATION_METRIC_NODE_CLASS_MAPPINGS
    from h3_icr.validation_metric_nodes import NODE_DISPLAY_NAME_MAPPINGS as VALIDATION_METRIC_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.validation_nodes import NODE_CLASS_MAPPINGS as VALIDATION_NODE_CLASS_MAPPINGS
    from h3_icr.validation_nodes import NODE_DISPLAY_NAME_MAPPINGS as VALIDATION_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.validation_perf_nodes import NODE_CLASS_MAPPINGS as VALIDATION_PERF_NODE_CLASS_MAPPINGS
    from h3_icr.validation_perf_nodes import NODE_DISPLAY_NAME_MAPPINGS as VALIDATION_PERF_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **BASE_NODE_CLASS_MAPPINGS,
    **POSTERIOR_NODE_CLASS_MAPPINGS,
    **PIXEL_NODE_CLASS_MAPPINGS,
    **TILED_NODE_CLASS_MAPPINGS,
    **UPSCALER_NODE_CLASS_MAPPINGS,
    **ATTN_NODE_CLASS_MAPPINGS,
    **SPARSE_NODE_CLASS_MAPPINGS,
    **ADAPTER_NODE_CLASS_MAPPINGS,
    **VALIDATION_NODE_CLASS_MAPPINGS,
    **VALIDATION_METRIC_NODE_CLASS_MAPPINGS,
    **VALIDATION_PERF_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **BASE_NODE_DISPLAY_NAME_MAPPINGS,
    **POSTERIOR_NODE_DISPLAY_NAME_MAPPINGS,
    **PIXEL_NODE_DISPLAY_NAME_MAPPINGS,
    **TILED_NODE_DISPLAY_NAME_MAPPINGS,
    **UPSCALER_NODE_DISPLAY_NAME_MAPPINGS,
    **ATTN_NODE_DISPLAY_NAME_MAPPINGS,
    **SPARSE_NODE_DISPLAY_NAME_MAPPINGS,
    **ADAPTER_NODE_DISPLAY_NAME_MAPPINGS,
    **VALIDATION_NODE_DISPLAY_NAME_MAPPINGS,
    **VALIDATION_METRIC_NODE_DISPLAY_NAME_MAPPINGS,
    **VALIDATION_PERF_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
