try:
    from .h3_icr.nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
    from .h3_icr.nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
    from .h3_icr.tiled_nodes import NODE_CLASS_MAPPINGS as TILED_NODE_CLASS_MAPPINGS
    from .h3_icr.tiled_nodes import NODE_DISPLAY_NAME_MAPPINGS as TILED_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:  # allows source-tree test collection where root is imported as __init__
    from h3_icr.nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
    from h3_icr.nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
    from h3_icr.tiled_nodes import NODE_CLASS_MAPPINGS as TILED_NODE_CLASS_MAPPINGS
    from h3_icr.tiled_nodes import NODE_DISPLAY_NAME_MAPPINGS as TILED_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**BASE_NODE_CLASS_MAPPINGS, **TILED_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BASE_NODE_DISPLAY_NAME_MAPPINGS, **TILED_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
